# file: postgresql/tasks/extensions.yml

- import_tasks: extensions/contrib.yml
  when: postgresql_ext_install_contrib
- import_tasks: extensions/dev_headers.yml
  when: postgresql_ext_install_dev_headers
- import_tasks: extensions/postgis.yml
  when: postgresql_ext_install_postgis
- import_tasks: extensions/pg_cron.yml
  when: postgresql_ext_install_pg_cron
- import_tasks: extensions/plpython.yml
  when: postgresql_ext_install_plpython
